### ISSUE TITLE
A desktop file for fonts?

### ISSUE THREAD

**Issue by hughsie** [projecthamster/apx#7]
This showed up today in Fedora rawhide: https://github.com/hughsie/createrepo_as_logs/blob/master/a/apx.log

Is that summary correct?! If it's supposed to be for the game, please consider writing and installing an AppData file with the application description and some screenshots, else it looks really bad in the GNOME and KDE Software Centers.

See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by tbaugis** [comment]
thanks for the report!
created appdata and filled it to my best knowledge. hope this will do!

**Comment by hughsie** [comment]
??
