### ISSUE TITLE
Hardcoded icon path in launcher

### ISSUE THREAD

**Issue by palob** [projecthamster/apx#8]
Hi,

currently the icon path specified in the created [.desktop launcher file](https://github.com/projecthamster/apx/blob/e978d9562e574f7e8675ee861d7f11530eb58e18/data/apx.desktop) is set to:
``Icon=/usr/share/apx/icons/apx.svg``

This prevents icon theming without editing the launcher file.

I'd like to ask you to change the icon location as well as the icon path line in the launcher according to the freedesktop.org standards.

Please find more info here:
http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
https://github.com/Foggalong/hardcode-fixer/wiki/What,-Why-&-How

According to the above resources standard icon locations are:

``/usr/share/icons/hicolor/[size]/apps/[icon name]``
``~/.local/share/icons/hicolor/[size]/apps/[icon name]``
or simply:
``/usr/share/pixmaps/[icon name]``

The corresponding standard icon line in the .desktop launcher is:
``Icon=[icon name]`` (without full path, without file extension)

for instance
``Icon=apx``

(for an icon ``apx.svg`` or ``apx.png`` stored in standard location

Could you please move the icon to one of those locations and adjust the icon path in the .desktop file accordingly?

**Comment by tbaugis** [comment]
@palob - sorry for such a delayed reply - icon has been moved now. i did not manage to make it work without the extension, so desktop file now reads ```Icon=/usr/share/icons/hicolor/scalable/apx.svg```

thank you for reporting the bug!

**Comment by palob** [comment]
Thanks, it really should work with just ``Icon=apx`` now though.
You may need to run ``gtk-update-icon-cache /usr/share/icons/hicolor`` or logout from your desktop session.

**Comment by tbaugis** [comment]
ya, tried it out (logging out is excessive -> alt+F2 -> "r" is enough) but
doesn't seem to be working.
let me know if and how you get it to work and i'll update the files then! :)

**Comment by Foggalong** [comment]
This issue isn't fixed btw, even if it's in the right location if the full path is used then it's still hardcoded :(

**Comment by tbaugis** [comment]
:'(

**Comment by bil-elmoussaoui** [comment]
@tbaugis Hey, in order to fix that you will have to add this line `window.set_icon_name("apx")`  to `BasicWindow` and change the icon value in the destkop file to `apx`. Reinstall the application and everything should work fine! :+1:
